name: birriadon
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0-241.0.dev <4.0.0"

dependencies:
  cloud_firestore: ^4.16.0
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.2
  intl: ^0.19.0
  syncfusion_flutter_charts: ^25.1.40
  week_of_year: ^2.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/TaquitoIcon.jpeg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FF0000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
