// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJz9YSAR3mEpYOF2-iNaqBqHrdKZcMxA',
    appId: '1:931258665733:web:a1e6faad61bcae005b456c',
    messagingSenderId: '931258665733',
    projectId: 'db-birria',
    authDomain: 'db-birria.firebaseapp.com',
    storageBucket: 'db-birria.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrBMOE93nTj2OgMkPwRibhI8DuTZgJhA',
    appId: '1:931258665733:android:31f49848fa747b255b456c',
    messagingSenderId: '931258665733',
    projectId: 'db-birria',
    storageBucket: 'db-birria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPBacKnMWVB87QuFNHz5BGp5trZn01etI',
    appId: '1:931258665733:ios:3403effdced1350c5b456c',
    messagingSenderId: '931258665733',
    projectId: 'db-birria',
    storageBucket: 'db-birria.appspot.com',
    iosBundleId: 'com.example.birriadon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPBacKnMWVB87QuFNHz5BGp5trZn01etI',
    appId: '1:931258665733:ios:c137b979db776b8e5b456c',
    messagingSenderId: '931258665733',
    projectId: 'db-birria',
    storageBucket: 'db-birria.appspot.com',
    iosBundleId: 'com.example.birriadon.RunnerTests',
  );
}
